"""Named-recipient app delivery orchestration (control-plane artifacts under ``.akc/delivery/``)."""

from __future__ import annotations

from akc.delivery.adapter import DistributionAdapter
from akc.delivery.adapters import (
    ALL_STUB_ADAPTERS,
    BOTH_MODE_DISTRIBUTION_PHASES,
    AppStoreReleaseAdapter,
    FirebaseAppDistributionAdapter,
    GooglePlayReleaseAdapter,
    TestFlightAdapter,
    WebInviteAdapter,
    collect_distribution_preflight_issues,
    enforce_adapter_preflight,
    iter_distribution_jobs,
    release_lanes_for_mode,
)
from akc.delivery.orchestrate import run_delivery_build_and_package
from akc.delivery.packaging_adapter import PackagingAdapter, PackagingResult
from akc.delivery.packaging_adapters import (
    ALL_PACKAGING_ADAPTERS,
    AndroidBuildPackagingAdapter,
    IosBuildPackagingAdapter,
    WebBundlePackagingAdapter,
    collect_packaging_preflight_issues,
    enforce_packaging_preflight,
    packaging_adapter_for,
)
from akc.delivery.types import (
    ActivationProof,
    AppProofStatus,
    ChannelState,
    ChannelStatus,
    DeliveryModelError,
    DeliveryPlatform,
    DeliveryRequestV1,
    DeliverySession,
    PerRecipientSessionState,
    PipelineStage,
    PlatformBuildSpec,
    PlatformChannels,
    ProviderProofStatus,
    RecipientDeliveryStatus,
    RecipientSpec,
    ReleaseLane,
    ReleaseMode,
    SessionActivationRollup,
    SessionPhase,
    StorePlatformLane,
    StoreReleaseState,
)
from akc.delivery.versioning import PlatformProviderVersions, derive_platform_provider_versions

__all__: list[str] = [
    "ALL_PACKAGING_ADAPTERS",
    "ALL_STUB_ADAPTERS",
    "BOTH_MODE_DISTRIBUTION_PHASES",
    "AndroidBuildPackagingAdapter",
    "ActivationProof",
    "AppProofStatus",
    "AppStoreReleaseAdapter",
    "ChannelState",
    "ChannelStatus",
    "DeliveryModelError",
    "DeliveryPlatform",
    "DeliveryRequestV1",
    "DeliverySession",
    "DistributionAdapter",
    "FirebaseAppDistributionAdapter",
    "GooglePlayReleaseAdapter",
    "IosBuildPackagingAdapter",
    "PackagingAdapter",
    "PackagingResult",
    "PerRecipientSessionState",
    "PlatformProviderVersions",
    "PipelineStage",
    "PlatformBuildSpec",
    "PlatformChannels",
    "ProviderProofStatus",
    "RecipientDeliveryStatus",
    "RecipientSpec",
    "ReleaseLane",
    "ReleaseMode",
    "SessionActivationRollup",
    "SessionPhase",
    "StorePlatformLane",
    "StoreReleaseState",
    "TestFlightAdapter",
    "WebBundlePackagingAdapter",
    "WebInviteAdapter",
    "collect_distribution_preflight_issues",
    "collect_packaging_preflight_issues",
    "derive_platform_provider_versions",
    "enforce_adapter_preflight",
    "enforce_packaging_preflight",
    "iter_distribution_jobs",
    "packaging_adapter_for",
    "release_lanes_for_mode",
    "run_delivery_build_and_package",
]
